Live Project Bonrix/myenv/userinterface/userinterface/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', views.index, name="index"),
    path('', views.loginpage, name="loginpage"),
    path('login', views.login),
    path('logout', views.logout),
    # path('multi_delete', views.multi_delete),
    path('registrationpage', views.registrationpage),
    path('register', views.register),
    path('ExpensiveCategory', views.ExpensiveCategory, name="ExpensiveCategory"),
    path('editExpensiveCategory/<int:id>', views.editExpensiveCategory),
    path('updateExpensiveCategory/<int:id>', views.updateExpensiveCategory),
    path('deleteExpensiveCategory/<int:id>', views.destroyExpensiveCategory),
    path('addnewExpensiveCategory', views.addnewExpensiveCategory),
    path('multi_deleteExpenseCategory', views.multi_deleteExpenseCategory),
    path('IncomeCategoryshow', views.IncomeCategoryshow, name="IncomeCategoryshow"),
    path('editIncomeCategory/<int:id>', views.editIncomeCategory),
    path('updateIncomeCategory/<int:id>', views.updateIncomeCategory),
    path('deleteIncomeCategory/<int:id>', views.destroyIncomeCategory),
    path('multi_deleteIncomeCategory', views.multi_deleteIncomeCategory),
    path('addnewIncomeCategory', views.addnewIncomeCategory),
    path('addincome_expense_ledger', views.addincome_expense_ledger),
    path('showBalance', views.showBalance, name="showBalance"),
    path('addnewBalance', views.addnewBalance),
    path('editBalance/<int:id>', views.editBalance),
    path('updateBalance/<int:id>', views.updateBalance),
    path('deleteBalance/<int:id>', views.destroyBalance),
    path('showMembers_vendor', views.showMembers_vendor, name="showMembers_vendor"),
    path('editMembers_vendor/<int:id>', views.editMembers_vendor),
    path('updateMembers_vendor/<int:id>', views.updateMembers_vendor),
    path('deleteMembers_vendor/<int:id>', views.destroyMembers_vendor),
    path('addnewMembers_vendor', views.addnewMembers_vendor),
    path('multi_deleteMembers_vendor', views.multi_deleteMembers_vendor),
    path('export_users_xls', views.export_users_xls),
    path('export_users_xlsImcome', views.export_users_xlsImcome),
    path('export_users_xlsImembers', views.export_users_xlsImembers),
    path('upload_file', views.upload_file),
    path('simple_upload', views.simple_upload),
    path('simple_uploadIncome', views.simple_uploadIncome),
    path('simple_uploadMembers_Vendors', views.simple_uploadMembers_Vendors),
    path('income_expense_ledgerValue', views.income_expense_ledgerValue),
    path('showincome_expense_ledger', views.showincome_expense_ledger, name="showincome_expense_ledger"),
    path('editIncome_expense_ledger/<int:id>', views.editIncome_expense_ledger),
    path('updateIncome_expense_ledger/<int:id>', views.updateIncome_expense_ledger),
    path('deleteIncome_expense_ledger/<int:id>', views.destroyIncome_expense_ledger),
    path('export_users_xlsLedger', views.export_users_xlsLedger),
    path('multi_deleteIncome_Expense_Ledger', views.multi_deleteIncome_Expense_Ledger),
    path('simple_uploadIncome_Expense_Ledger', views.simple_uploadIncome_Expense_Ledger),
    path('demo/<int:id>', views.demo,name='demo'),
    path('cashWithdrawal', views.cashWithdrawal),
    path('cashWithdrawEntryValue',views.cashWithdrawEntryValue),
    path('cashDeposit',views.cashDeposit),
    path('cashDepositEntryValue',views.cashDepositEntryValue),
    path('sample_Excel',views.sample_Excel),
    path('download_excel_data',views.download_excel_data),
    path('export_csv',views.export_csv),
    path('demo/file_store',views.file_store,name="file_store"),
    path('destroyFile/<int:id>',views.destroyFile,name='deletefile'),
    path('showMembersDetails',views.showMembersDetails,name='showMembersDetails'),
    path('addnewMembersDetails',views.addnewMembersDetails),
    path('editMembersDetails/<int:id>',views.editMembersDetails),
    path('updateMembersDetails/<int:id>',views.updateMembersDetails),
    path('deletedMembersDetails/<int:id>',views.destroyMembersDetails),
    path('export_users_xlsImembersDetails',views.export_users_xlsImembersDetails),


    # path('showincome_expense_ledger2', views.showincome_expense_ledger2, name="showincome_expense_ledger2"),
]


if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Live Project Bonrix/myenv/userinterface/myapp/models.py
from django.db import models


class User_Society_deatils(models.Model):
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=20)
    contact_name = models.CharField(max_length=500)
    otp = models.IntegerField(default=459)
    moblie_no = models.CharField(unique=True, max_length=10)
    society_name = models.CharField(max_length=500)
    society_address = models.CharField(max_length=500)
    city = models.CharField(max_length=200)
    pin_code = models.CharField(max_length=10)
    country = models.CharField(max_length=100)
    society_registration_number = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_verfied = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, blank=False)
    updated_at = models.DateTimeField(auto_now=True, blank=False)


# class Employee(models.Model):
#     name = models.CharField(max_length=100)
#     email = models.EmailField()
#     contact = models.CharField(max_length=15)
#     age = models.CharField(max_length=3)
#     status = models.BooleanField(default=False)
#
#     class Meta:
#         db_table = "employee"


class ExpenseCategory(models.Model):
    category_name = models.CharField(unique=True, max_length=200)


class IncomeCategory(models.Model):
    category_name = models.CharField(unique=True, max_length=200)


class BalanceValue(models.Model):
    account = models.CharField(unique=True, max_length=100)
    balance_amount = models.FloatField(max_length=500)


class Members_Vendor_Account(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)


class MembersDeatils(models.Model):
    flatNo = models.CharField(max_length=200)
    primaryName = models.CharField(max_length=200, null=True, blank=True)
    primaryContactNo = models.CharField(max_length=10, null=True, blank=True)
    secondaryName = models.CharField(max_length=200, null=True, blank=True)
    secondaryContactNo = models.CharField(max_length=10, null=True, blank=True)
    accountingName = models.CharField(max_length=200, null=True, blank=True)
    whatsappContactNo = models.CharField(max_length=10, null=True, blank=True)


class MembersDeatilsValue(models.Model):
    flatNo = models.CharField(max_length=200)
    primaryName = models.CharField(max_length=200, null=True, blank=True)
    primaryContactNo = models.CharField(max_length=10, null=True, blank=True)
    secondaryName = models.CharField(max_length=200, null=True, blank=True)
    secondaryContactNo = models.CharField(max_length=10, null=True, blank=True)
    accountingName = models.CharField(max_length=200, null=True, blank=True)
    whatsappContactNo = models.CharField(max_length=10, null=True, blank=True)
    email = models.EmailField(unique=True)
    residence = models.CharField(max_length=100)


class Income_Expense_LedgerValue1(models.Model):
    dateOn = models.DateField()
    type = models.CharField(max_length=100)
    amount = models.FloatField(max_length=100)
    category_header = models.CharField(max_length=100, null=True, blank=True)
    from_or_to_account = models.CharField(max_length=100, null=True, blank=True)
    transaction_type = models.CharField(max_length=100)
    transaction_details = models.CharField(max_length=100, null=True, blank=True)
    voucherNo_or_invoiceNo = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='images/', verbose_name='image', null=True, blank=True)
    remark = models.TextField(max_length=500, null=True, blank=True)
    opening_balance_cash = models.FloatField(max_length=100)
    closing_balance_cash = models.FloatField(max_length=100)
    opening_balance_bank = models.FloatField(max_length=100)
    closing_balance_bank = models.FloatField(max_length=100)
    entry_time = models.DateTimeField(null=True, blank=True)


class FileStoreValue1(models.Model):
    income_Expense_LedgerId = models.ForeignKey(Income_Expense_LedgerValue1, on_delete=models.CASCADE)
    text = models.CharField(max_length=100, null=True, blank=True)
    type_file = models.FileField(upload_to='filestore/', verbose_name='file', null=True, blank=True)

Live Project Bonrix/myenv/userinterface/myapp/forms.py
from django import forms
from .models import ExpenseCategory, IncomeCategory, Income_Expense_LedgerValue1, BalanceValue, \
    Members_Vendor_Account, FileStoreValue1, MembersDeatilsValue


# class EmployeeForm(forms.ModelForm):
#     class Meta:
#         model = Employee
#         fields = ['name', 'contact', 'email', 'age']  # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
#         widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
#                    'email': forms.EmailInput(attrs={'class': 'form-control'}),
#                    'contact': forms.TextInput(attrs={'class': 'form-control'}),
#                    'age': forms.TextInput(attrs={'class': 'form-control'})}


class ExpensiveCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['category_name']  # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = {'category_name': forms.TextInput(attrs={'class': 'form-control'})
                   }


class IncomeCategoryForm(forms.ModelForm):
    class Meta:
        model = IncomeCategory
        fields = ['category_name']  # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = {'category_name': forms.TextInput(attrs={'class': 'form-control'})
                   }


class Members_Vendor_AccountForm(forms.ModelForm):
    class Meta:
        model = Members_Vendor_Account
        fields = ['name']  # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'})
                   }


class MembersDeatilsForm(forms.ModelForm):
    class Meta:
        model = MembersDeatilsValue
        fields = ['flatNo', 'primaryName', 'primaryContactNo', 'secondaryName', 'secondaryContactNo', 'accountingName',
                  'whatsappContactNo', 'email', 'residence']  # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = {'flatNo': forms.TextInput(attrs={'class': 'form-control'}),
                   'primaryName': forms.TextInput(attrs={'class': 'form-control'}),
                   'primaryContactNo': forms.TextInput(attrs={'class': 'form-control'}),
                   'secondaryName': forms.TextInput(attrs={'class': 'form-control'}),
                   'secondaryContactNo': forms.TextInput(attrs={'class': 'form-control'}),
                   'accountingName': forms.TextInput(attrs={'class': 'form-control'}),
                   'whatsappContactNo': forms.TextInput(attrs={'class': 'form-control'}),
                   'email': forms.TextInput(attrs={'class': 'form-control'}),
                   'residence': forms.TextInput(attrs={'class': 'form-control'})
                   }


class BalanceFrom(forms.ModelForm):
    class Meta:
        model = BalanceValue
        fields = ['balance_amount']  # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = {'balance_amount': forms.TextInput(attrs={'class': 'form-control'})
                   }


class Income_Expense_LedgerForm(forms.ModelForm):
    class Meta:
        model = Income_Expense_LedgerValue1
        fields = ['dateOn', 'type', 'amount', 'category_header', 'from_or_to_account', 'transaction_type',
                  'transaction_details',
                  'voucherNo_or_invoiceNo', 'remark', 'opening_balance_cash', 'closing_balance_cash',
                  'opening_balance_bank',
                  'closing_balance_bank']
        widgets = {'dateOn': forms.DateInput(attrs={'class': 'form-control'}),
                   'type': forms.TextInput(attrs={'class': 'form-control'}),
                   'amount': forms.TextInput(attrs={'class': 'form-control'}),
                   'category_header': forms.TextInput(attrs={'class': 'form-control'}),
                   'from_or_to_account': forms.TextInput(attrs={'class': 'form-control'}),
                   'transaction_type': forms.TextInput(attrs={'class': 'form-control'}),
                   'transaction_details': forms.TextInput(attrs={'class': 'form-control'}),
                   'voucherNo_or_invoiceNo': forms.TextInput(attrs={'class': 'form-control'}),
                   'remark': forms.Textarea(attrs={'class': 'form-control'}),
                   'opening_balance_cash': forms.TextInput(attrs={'class': 'form-control'}),
                   'closing_balance_cash': forms.TextInput(attrs={'class': 'form-control'}),
                   'opening_balance_bank': forms.TextInput(attrs={'class': 'form-control'}),
                   'closing_balance_bank': forms.TextInput(attrs={'class': 'form-control'}),
                   'entry_time': forms.DateInput(attrs={'class': 'form-control'})
                   }


class FileStoreForm(forms.ModelForm):
    class Meta:
        model = FileStoreValue1
        fields = ['text', 'type_file']  # https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = {'text': forms.TextInput(attrs={'class': 'form-control'}),
                   'type_file': forms.FileField()
                   }

Live Project Bonrix/myenv/userinterface/myapp/templates/addBalance.html
{% extends 'bash.html' %}
{% load static %}
{% block content %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<style>
.home-content .sales-boxes .recent-sales{
  width: 100%;
  background: #fff;
  padding: 20px 30px;
  margin: 0 20px;
  border-radius: 12px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}

</style>
<section class="home-section">
    <nav>
        <div class="sidebar-button">
            <i class='bx bx-menu sidebarBtn'></i>
            <span class="dashboard">BALANCE</span>
        </div>
        <div class="search-box">
            <input type="text" placeholder="Search...">
            <i class='bx bx-search'></i>
        </div>
        <div class="profile-details">
            <!--        <img src="images/profile.jpg" alt="">-->
            <i class="fa fa-user" aria-hidden="true" style="margin-left:40px;"></i>
            <a href="/logout" style="margin-left:10px; text-decoration:none;"> Logout </a>
        </div>
    </nav>

    <div class="home-content">
        <div class="sales-boxes">
            <div class="recent-sales box">
                <div class="title">New Balance Added</div>
                <hr>
                <div class="sales-details">
                    <form method="POST" class="post-form" action="/addnewBalance">
                        {% csrf_token %}
                        <div class="container">
                            <br>
                            <div class="form-group row">


                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Balance Name:</label>
                                    <div class="col-sm-6">
                                        <select class="col-sm-4" name="type">
                                            <option selected>----select-----</option>
                                            <option value="Case">Case</option>
                                            <option value="Bank">Bank</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Balance Amount:</label>
                                    <div class="col-sm-3">
                                       <input type="text"  name="balnce_amount">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-1 col-form-label"></label>
                                    <div class="col-sm-4">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

Live Project Bonrix/myenv/userinterface/myapp/templates/addExpensiveCategory.html
{% extends 'bash.html' %}
{% load static %}
{% block content %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<style>
.home-content .sales-boxes .recent-sales{
  width: 100%;
  background: #fff;
  padding: 20px 30px;
  margin: 0 20px;
  border-radius: 12px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}
</style>

<section class="home-section">
    <nav>
      <div class="sidebar-button">
        <i class='bx bx-menu sidebarBtn'></i>
        <span class="dashboard">EXPENSE</span>
      </div>
      <div class="search-box">
        <input type="text" placeholder="Search...">
        <i class='bx bx-search' ></i>
      </div>
      <div class="profile-details">
<!--        <img src="images/profile.jpg" alt="">-->
        <i class="fa fa-user" aria-hidden="true" style="margin-left:40px;"></i>
        <a href="/logout"  style="margin-left:10px; text-decoration:none;"> Logout </a>
      </div>
    </nav>

    <div class="home-content">


      <div class="sales-boxes">
        <div class="recent-sales box">
          <div class="title">New Expense Category  Added</div>
            <hr>
          <div class="sales-details">
         <form method="POST" class="post-form" action="/addnewExpensiveCategory">
   {% csrf_token %}
  <div class="container">
 <br>
  <div class="form-group row">


   <div class="form-group row">
  <label class="col-sm-2 col-form-label">Category Name:</label>
  <div class="col-sm-4">
    {{ form.category_name }}
  </div>
   </div>

  <div class="form-group row">
  <label class="col-sm-1 col-form-label"></label>
  <div class="col-sm-4">
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
   </div>
  </div>
  </div>
 </form>
          </div>
        </div>
      </div>
    </div>
</section>


{% endblock %}

Live Project Bonrix/myenv/userinterface/myapp/templates/editExpensiveCategory.html
{% extends 'bash.html' %}
{% load static %}
{% block content %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<style>
.home-content .sales-boxes .recent-sales{
  width: 100%;
  background: #fff;
  padding: 20px 30px;
  margin: 0 20px;
  border-radius: 12px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}
</style>

<section class="home-section">
    <nav>
      <div class="sidebar-button">
        <i class='bx bx-menu sidebarBtn'></i>
        <span class="dashboard">EXPENSE</span>
      </div>
      <div class="search-box">
        <input type="text" placeholder="Search...">
        <i class='bx bx-search' ></i>
      </div>
      <div class="profile-details">
          <i class="fa fa-user" aria-hidden="true" style="margin-left:40px;"></i>
        <a href="/logout"  style="margin-left:10px; text-decoration:none;"> Logout </a>
      </div>
    </nav>

    <div class="home-content">


      <div class="sales-boxes">
        <div class="recent-sales box">
          <div class="title">Update Expense Category Details</div>
            <hr>
          <div class="sales-details">
        <form method="POST" class="post-form" action="/updateExpensiveCategory/{{expensiveCategory.id}}">
   {% csrf_token %}
  <div class="container">
 <br>
  <div class="form-group row">

  <div class="form-group row">
  <label class="col-sm-2 col-form-label">Category Id:</label>
  <div class="col-sm-4">
   <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ expensiveCategory.id }}"/>
  </div>
   </div>
   <div class="form-group row">
  <label class="col-sm-2 col-form-label">Category Name:</label>
  <div class="col-sm-4">
   <input type="text" class="form-control" name="category_name" id="id_name" required maxlength="100" value="{{ expensiveCategory.category_name }}" />
  </div>
   </div>
  <div class="form-group row">
  <label class="col-sm-1 col-form-label"></label>
  <div class="col-sm-4">
  <button type="submit" class="btn btn-success btn-lg">Update</button>
  </div>
   </div>
  </div>
  </div>
 </form>
          </div>
        </div>
      </div>
    </div>
</section>



{% endblock %}

Live Project Bonrix/myenv/userinterface/myapp/templates/editMembersDetails.html
{% extends 'bash.html' %}
{% load static %}
{% block content %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<style>
.home-content .sales-boxes .recent-sales{
  width: 100%;
  background: #fff;
  padding: 20px 30px;
  margin: 0 20px;
  border-radius: 12px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}

</style>
<section class="home-section">
    <nav>
        <div class="sidebar-button">
            <i class='bx bx-menu sidebarBtn'></i>
            <span class="dashboard">MEMBERS_VENDORS</span>
        </div>
        <div class="search-box">
            <input type="text" placeholder="Search...">
            <i class='bx bx-search'></i>
        </div>
        <div class="profile-details">
            <i class="fa fa-user" aria-hidden="true" style="margin-left:40px;"></i>
            <a href="/logout" style="margin-left:10px; text-decoration:none;"> Logout </a>
        </div>
    </nav>

    <div class="home-content">


        <div class="sales-boxes">
            <div class="recent-sales box">
                <div class="title">Update Members-Vendor Details</div>
                <hr>
                <div class="sales-details">
                    <form method="POST" class="post-form" action="/updateMembersDetails/{{membersDetails.id}}">
                        {% csrf_token %}
                        <div class="container">
                            <br>
                            <div class="form-group row">

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label"> Id:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="id" id="id_id" required
                                               maxlength="20" value="{{ membersDetails.id }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Flat No:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="flatNo" id="id_flatNo" required
                                               maxlength="100" value="{{ membersDetails.flatNo }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Primary Name:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="primaryName" id="id_primaryName" required
                                               maxlength="100" value="{{ membersDetails.primaryName }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Primary ContactNo:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="primaryContactNo" id="id_primaryContactNo" required
                                               maxlength="100" value="{{ membersDetails.primaryContactNo }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Secondary Name:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="secondaryName" id="id_secondaryName" required
                                               maxlength="100" value="{{ membersDetails.secondaryName }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Secondary ContactNo:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="secondaryContactNo" id="id_secondaryContactNo" required
                                               maxlength="100" value="{{ membersDetails.secondaryContactNo }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Accounting Name:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="accountingName" id="id_accountingName" required
                                               maxlength="100" value="{{ membersDetails.accountingName }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Whatsapp ContactNo:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="whatsappContactNo" id="id_whatsappContactNo" required
                                               maxlength="100" value="{{ membersDetails.whatsappContactNo }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Email:</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="email" id="id_email"
                                               required
                                               maxlength="100" value="{{ membersDetails.email }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Residence</label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="residence" id="id_residence"
                                               required
                                               maxlength="100" value="{{ membersDetails.residence }}"/>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-sm-1 col-form-label"></label>
                                    <div class="col-sm-4">
                                        <button type="submit" class="btn btn-success btn-lg">Update</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

Live Project Bonrix/myenv/userinterface/myapp/templates/editMembers_vendor.html
{% extends 'bash.html' %}
{% load static %}
{% block content %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<style>
.home-content .sales-boxes .recent-sales{
  width: 100%;
  background: #fff;
  padding: 20px 30px;
  margin: 0 20px;
  border-radius: 12px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}
</style>
<section class="home-section">
    <nav>
      <div class="sidebar-button">
        <i class='bx bx-menu sidebarBtn'></i>
        <span class="dashboard">MEMBERS_VENDORS</span>
      </div>
      <div class="search-box">
        <input type="text" placeholder="Search...">
        <i class='bx bx-search' ></i>
      </div>
      <div class="profile-details">
          <i class="fa fa-user" aria-hidden="true" style="margin-left:40px;"></i>
        <a href="/logout"  style="margin-left:10px; text-decoration:none;"> Logout </a>
      </div>
    </nav>

    <div class="home-content">


      <div class="sales-boxes">
        <div class="recent-sales box">
          <div class="title">Update Members-Vendor Details</div>
            <hr>
          <div class="sales-details">
        <form method="POST" class="post-form" action="/updateMembers_vendor/{{membersVendor.id}}">
   {% csrf_token %}
  <div class="container">
 <br>
  <div class="form-group row">

  <div class="form-group row">
  <label class="col-sm-3 col-form-label">Members Id:</label>
  <div class="col-sm-3">
   <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ membersVendor.id }}"/>
  </div>
   </div>
   <div class="form-group row">
  <label class="col-sm-3 col-form-label">Members-vendors Name:</label>
  <div class="col-sm-3">
   <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ membersVendor.name }}" />
  </div>
   </div>
  <div class="form-group row">
  <label class="col-sm-1 col-form-label"></label>
  <div class="col-sm-4">
  <button type="submit" class="btn btn-success btn-lg">Update</button>
  </div>
   </div>
  </div>
  </div>
 </form>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}